version: "2"
services:
  db:
    container_name: "db"
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=ticketmonster
      - POSTGRES_PASSWORD=ticketmonster-docker
  modcluster:
    container_name: "modcluster"
    image: karm/mod_cluster-master-dockerhub
    environment:
      - MODCLUSTER_NET=192. 172. 10. 179. 213.
      - MODCLUSTER_PORT=80
    ports:
      - "80:80"
  wildfly:
    container_name: "wildfly"
    #image: rafabene/wildfly-ticketmonster-ha
    image: compose-wildfly
    #build: ../Dockerfiles/ticketmonster-ha/
    # must use absolute path or link to github repo with ansible-container
    build: /sharedfolder/github.com/rafabene/devops-demo/Dockerfiles/ticketmonster-ha/
    links:
      - db
      - modcluster
